"""empty message

Revision ID: 7e9fe88a7568
Revises: 
Create Date: 2023-01-09 23:46:02.627440

"""
import uuid
import datetime
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9fe88a7568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    identity_role_table = op.create_table('identity_role',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_datetime', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('modified_datetime', sa.DATETIME(timezone=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ### Run Seed
    op.bulk_insert(
        identity_role_table,
        [
            {
                'id': uuid.uuid4(),
                'name': 'admin',
                'created_by': 'SYSTEM',
                'created_datetime': datetime.datetime.now()
            },
            {
                'id': uuid.uuid4(),
                'name': 'user',
                'created_by': 'SYSTEM',
                'created_datetime': datetime.datetime.now()
            }
        ]
    )
    # ### end


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_role')
    # ### end Alembic commands ###

